[project]
name = "idhagnbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "su226", email = "thesu226@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "arclet-entari[cron]>=0.19.0rc2",
    "entari-plugin-database>=0.3.3",
    "entari-plugin-permission>=0.1.1",
    "entari-plugin-server[fastapi]>=0.7.4",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
    "pygobject>=3.56.3",
]

[project.optional-dependencies]
sort = [
    "pyicu>=2.16.2",
]
jsonc = [
    "json-with-comments>=1.2.10",
]
crypto = [
    "pycryptodome>=3.23.0",
]
psutil = [
    "psutil>=7.2.2",
]
cv2 = [
    "opencv-python-headless>=5.0.0.93",
]

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"

[tool.ruff.lint]
extend-select = ["ALL"]
ignore = [
    "ANN401", # any-type
    "ARG", # flake8-unused-arguments
    "B008", # function-call-in-default-argument
    "B010", # set-attr-with-constant
    "BLE001", # blind-except (自动忽略 logging.exception 但不忽略 loguru.exception)
    "C901", # complex-structure
    "CPY001", # missing-copyright-notice
    "D", # pydocstyle
    "DTZ", # flake8-datetimez
    "E402", # module-import-not-at-top-of-file
    "E741", # ambiguous-variable-name
    "EM", # flake8-errmsg
    "FA100", # future-rewritable-type-annotation
    "FBT001", # boolean-type-hint-positional-argument
    "FBT002", # boolean-default-value-positional-argument
    "FIX", # flake8-fixme
    "INP001", # implicit-namespace-package
    "N818", # error-suffix-on-exception-name
    "PERF203", # try-except-in-loop
    "PLC0415", # import-outside-top-level
    "PLR0904", # too-many-public-methods
    "PLR0911", # too-many-return-statements
    "PLR0912", # too-many-branches
    "PLR0913", # too-many-arguments
    "PLR0914", # too-many-locals
    "PLR0915", # too-many-statements
    "PLR0916", # too-many-boolean-expressions
    "PLR0917", # too-many-positional-arguments
    "PLR2004", # magic-value-comparison
    "PLW0603", # global-statement
    "RUF001", # ambiguous-unicode-character-string
    "RUF002", # ambiguous-unicode-character-docstring
    "RUF003", # ambiguous-unicode-character-comment
    "S101", # assert
    "S311", # suspicious-non-cryptographic-random-usage
    "S603", # subprocess-without-shell-equals-true (容易误报)
    "S607", # start-process-with-partial-path
    "SIM105", # suppressible-exception
    "SLF001", # private-member-access
    "TD002", # missing-todo-author
    "TD003", # missing-todo-link
    "TRY003", # raise-vanilla-args
    "TC001", # typing-only-first-party-import
    "TC002", # typing-only-third-party-import
    "TC003", # typing-only-standard-library-import
]

[dependency-groups]
lint = [
    "ruff>=0.15.21",
    "ty>=0.0.58",
]
stubs = [
    "pygobject-stubs>=2.17.0",
    "types-croniter>=6.2.4.20260711",
    "types-psutil>=7.2.2.20260518",
]
