"""initial version

迁移 ID: 477dc8738e42
父迁移:
创建时间: 2026-03-31 19:12:09.248780

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
  from collections.abc import Sequence

revision: str = "477dc8738e42"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("idhagnbot_regex_counter",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "idhagnbot_regex_counter_counted",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("time", sa.DateTime(), nullable=False),
    sa.Column("scene_id", sa.String(), nullable=False),
    sa.Column("counter_id", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=False),
    sa.Column("match", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_idhagnbot_regex_counter_counted")),
    info={"bind_key": "regex_counter"},
  )
  # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("idhagnbot_regex_counter_counted")
  # ### end Alembic commands ###
