"""Use database instead of dict

迁移 ID: 5ed5f6c8ff35
父迁移:
创建时间: 2026-03-25 23:05:16.976588

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
  from collections.abc import Sequence

revision: str = "5ed5f6c8ff35"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("idhagnbot_repeat",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "idhagnbot_repeat_last_message",
    sa.Column("scene_id", sa.String(), nullable=False),
    sa.Column("run_id", sa.Integer(), nullable=False),
    sa.Column("message", sa.String(), nullable=False),
    sa.Column("received_count", sa.Integer(), nullable=False),
    sa.Column("sending_count", sa.Integer(), nullable=False),
    sa.Column("sent_count", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("scene_id", name=op.f("pk_idhagnbot_repeat_last_message")),
    info={"bind_key": "repeat"},
  )
  # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("idhagnbot_repeat_last_message")
  # ### end Alembic commands ###
