"""initial version

迁移 ID: 102f32e1eac2
父迁移:
创建时间: 2026-03-23 17:41:47.261050

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
  from collections.abc import Sequence

revision: str = "102f32e1eac2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("idhagnbot_fallback",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "idhagnbot_fallback_exception_suppressed_scene",
    sa.Column("scene_id", sa.String(), nullable=False),
    sa.Column("until", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint(
      "scene_id",
      name=op.f("pk_idhagnbot_fallback_exception_suppressed_scene"),
    ),
    info={"bind_key": "fallback"},
  )
  op.create_table(
    "idhagnbot_fallback_im_bot_suppressed_user",
    sa.Column("platform", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint(
      "platform",
      "user_id",
      name=op.f("pk_idhagnbot_fallback_im_bot_suppressed_user"),
    ),
    info={"bind_key": "fallback"},
  )
  # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("idhagnbot_fallback_im_bot_suppressed_user")
  op.drop_table("idhagnbot_fallback_exception_suppressed_scene")
  # ### end Alembic commands ###
