"""initial version

迁移 ID: d839fa7f93ef
父迁移:
创建时间: 2026-04-15 00:04:22.899204

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
  from collections.abc import Sequence

revision: str = "d839fa7f93ef"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("idhagnbot_lang",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "idhagnbot_lang_scene_locale",
    sa.Column("scene_id", sa.String(), nullable=False),
    sa.Column("locale", sa.String(), nullable=False),
    sa.Column("force", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint("scene_id", name=op.f("pk_idhagnbot_lang_scene_locale")),
    info={"bind_key": "lang"},
  )
  op.create_table(
    "idhagnbot_lang_user_locale",
    sa.Column("platform", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=False),
    sa.Column("locale", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("platform", "user_id", name=op.f("pk_idhagnbot_lang_user_locale")),
    info={"bind_key": "lang"},
  )
  # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("idhagnbot_lang_user_locale")
  op.drop_table("idhagnbot_lang_scene_locale")
  # ### end Alembic commands ###
