"""initial version

迁移 ID: e68842120d6f
父迁移: 
创建时间: 2025-08-03 17:05:24.857993

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e68842120d6f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('idhagnbot_link_parser',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idhagnbot_link_parser_last_state',
    sa.Column('scene', sa.String(), nullable=False),
    sa.Column('last_state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('scene', name=op.f('pk_idhagnbot_link_parser_last_state')),
    info={'bind_key': 'link_parser'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idhagnbot_link_parser_last_state')
    # ### end Alembic commands ###
