"""initial version

迁移 ID: 9ad15d1b8688
父迁移:
创建时间: 2026-04-21 17:29:28.150473

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
  from collections.abc import Sequence

revision: str = "9ad15d1b8688"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("idhagnbot_luck",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "idhagnbot_luck_luck",
    sa.Column("platform", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=False),
    sa.Column("date", sa.Date(), nullable=False),
    sa.Column("value", sa.Integer(), nullable=False),
    sa.Column("do", sa.String(), nullable=False),
    sa.Column("dont", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("platform", "user_id", name=op.f("pk_idhagnbot_luck_luck")),
    info={"bind_key": "luck"},
  )
  # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("idhagnbot_luck_luck")
  # ### end Alembic commands ###
