"""ignore

迁移 ID: 483958b6b961
父迁移: 9f5a7fa9706e
创建时间: 2025-06-02 18:13:15.980335

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
  from collections.abc import Sequence

revision: str = "483958b6b961"
down_revision: str | Sequence[str] | None = "9f5a7fa9706e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "idhagnbot_openai_ignore",
    sa.Column("scene", sa.String(), nullable=False),
    sa.Column("time", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("scene", name=op.f("pk_idhagnbot_openai_ignore")),
    info={"bind_key": "openai"},
  )
  with op.batch_alter_table("idhagnbot_openai_history", schema=None) as batch_op:
    batch_op.add_column(sa.Column("ignored", sa.Boolean(), server_default="0", nullable=False))

  # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table("idhagnbot_openai_history", schema=None) as batch_op:
    batch_op.drop_column("ignored")

  op.drop_table("idhagnbot_openai_ignore")
  # ### end Alembic commands ###
