"""initial version

迁移 ID: 9f5a7fa9706e
父迁移: 
创建时间: 2025-05-30 19:31:23.076645

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9f5a7fa9706e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('openai',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idhagnbot_openai_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', native_enum=False), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('superuser', sa.Boolean(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idhagnbot_openai_history')),
    info={'bind_key': 'openai'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idhagnbot_openai_history')
    # ### end Alembic commands ###
