"""initial version

迁移 ID: 68aa680e87bb
父迁移:
创建时间: 2026-03-31 23:33:50.858686

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
  from collections.abc import Sequence

revision: str = "68aa680e87bb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("idhagnbot_aspect",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "idhagnbot_aspect_aspect",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("scene_id", sa.String(), nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_idhagnbot_aspect_aspect")),
    sa.UniqueConstraint("scene_id", "title", name=op.f("uq_idhagnbot_aspect_aspect_scene_id")),
    info={"bind_key": "aspect"},
  )
  # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("idhagnbot_aspect_aspect")
  # ### end Alembic commands ###
