"""initial version

迁移 ID: 14d89e232e2b
父迁移: 
创建时间: 2025-09-19 21:42:17.233039

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '14d89e232e2b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('idhagnbot_quote',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idhagnbot_quote_sent_quote',
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('scene_id', 'message_id', name=op.f('pk_idhagnbot_quote_sent_quote')),
    info={'bind_key': 'quote'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idhagnbot_quote_sent_quote')
    # ### end Alembic commands ###
