"""record matcher call

迁移 ID: 264c6d398c3b
父迁移: f59af61c4219
创建时间: 2026-06-18 14:29:41.510380

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
  from collections.abc import Sequence

revision: str = "264c6d398c3b"
down_revision: str | Sequence[str] | None = "f59af61c4219"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "idhagnbot_chat_record_matcher_call",
    sa.Column("record_id", sa.Integer(), nullable=False),
    sa.Column("time", sa.DateTime(), nullable=False),
    sa.Column("matcher_type", sa.String(), nullable=False),
    sa.Column("scene_id", sa.String(), nullable=True),
    sa.Column("message_id", sa.String(), nullable=True),
    sa.Column("plugin_id", sa.String(), nullable=True),
    sa.Column("module_name", sa.String(), nullable=True),
    sa.Column("lineno", sa.Integer(), nullable=True),
    sa.Column("command_name", sa.String(), nullable=True),
    sa.Column("command_alias", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("record_id", name=op.f("pk_idhagnbot_chat_record_matcher_call")),
    info={"bind_key": "chat_record"},
  )
  # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("idhagnbot_chat_record_matcher_call")
  # ### end Alembic commands ###
