"""record outgoing

迁移 ID: f59af61c4219
父迁移: fbdb117674e7
创建时间: 2025-12-25 22:58:16.328678

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
  from collections.abc import Sequence

revision: str = "f59af61c4219"
down_revision: str | Sequence[str] | None = "fbdb117674e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table("idhagnbot_chat_record_message", schema=None) as batch_op:
    batch_op.add_column(sa.Column("outgoing", sa.Boolean(), server_default="0", nullable=False))
    batch_op.add_column(sa.Column("caused_by", sa.String(), nullable=True))

  # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
  if name:
    return
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table("idhagnbot_chat_record_message", schema=None) as batch_op:
    batch_op.drop_column("caused_by")
    batch_op.drop_column("outgoing")

  # ### end Alembic commands ###
