"""initial version

迁移 ID: fbdb117674e7
父迁移: 
创建时间: 2025-09-12 23:04:47.797507

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fbdb117674e7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('idhagnbot_chat_record',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idhagnbot_chat_record_message',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_idhagnbot_chat_record_message')),
    info={'bind_key': 'chat_record'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idhagnbot_chat_record_message')
    # ### end Alembic commands ###
